export interface BnaClassRoutineModel {
    CourseSectionName : string,
    SemesterName : string,
    RoomNo : any,
    Date : Date, 
    DayName : string,
    WeekName : string,
    WeekStartDate : Date,
    WeekEndDate : Date,
    ExtraCurriculamPeriod : string,
    Period1 : string,
    Period2 : string,
    Period3 : string,
    Period4 : string,
    Period5 : string,
    Period6 : string,
    StandEasyPeriod : string,
    LunchPeriod : string,
    CorrectivePeriod : string,
    AfternoonActivitiesGamePeriod : string,
    SelfStudyPeriod : string
}